############################### Backend App
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stackjudge-master
  name: app-backend
  labels:
    app: app-backend-label
spec:
  replicas: 1
  selector:
    matchLabels:
      service: app-backend
  template:
    metadata:
      labels:
        app: app-backend-label
        service: app-backend
    spec:
      containers:
        - name: app-backend
          image: kbalazsworks/stackjudge_backend:master
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: SERVER_PORT
              value: "41000"
            - name: SERVER_ENV
              value: "LOCAL_VAGRANT"
            - name: HEALTH_CHECK_ENV_VAR_TEST
              value: "env var test"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/stackjudge"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin_pass"
#            - name: IS_SEARCH_BOX_LOG_ENABLED"
#              value: False
            - name: ENV_SEARCHLY_URL
              value: ""
            - name: HTTP_CORS_ORIGINS
              value: "http://localhost:4200"
#            - name: AWS_S3_CDN_BUCKET
#              value: "stackjudge-cdn-dev-eu-central-1"
#            - name: AWS_ACCESS_KEY
#              value: "AKIA5PU76MZEYED5O2EG"
#            - name: AWS_SECRET_KEY
#              value: "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"
#            - name: FACEBOOK_CLIENT_ID
#              value: "6256044054421319"
#            - name: FACEBOOK_CLIENT_SECRET
#              value: "02d0121396bc2c5f2a3e5713a620a7c2"
#            - name: FACEBOOK_CALLBACK_URL
#              value: "https://192.168.33.10/account/facebook-callbackd"
#            - name: AUTH_JWT_SECRET
#              value: "12345678901234567890123456789012"
#            - name: SITE_DOMAIN
#              value: "https://192.168.33.10"
#            - name: SERVER_SSL_ENABLED
#              value: True
#            - name: SITE_FRONTEND_DOMAIN
#              value: "http://localhost:4200"
#            - name: SPRING_REDIS_HOST
#              value: "sj_backend_redis"
#            - name: SPRING_REDIS_PASSWORD
#              value: ""
#            - name: SPRING_REDIS_PORT
#              value: "6379"
#            - name: GOOGLE_MAPS_KEY
#              value: "asd"
#            - name: REDIS_ASPECT_CACHE_ENABLED
#              value: False
#            - name: SERVER_SSL_KEY_STORE
#              value: "classpath:keystore/v2/sjdev.p12"
#            - name: SERVER_SSL_KEY_STORE_PASSWORD
#              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  namespace: stackjudge-master
  name: app-backend
  labels:
    app: app-backend-label
    service: app-backend
spec:
  type: LoadBalancer
  selector:
    app: app-backend-label
    service: app-backend
  ports:
    - name: "http"
      protocol: TCP
      port: 41000
      targetPort: 80
---
############################### Backend App - PSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stackjudge-master
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          imagePullPolicy: Always
          resources: {}
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin_pass
            - name: POSTGRES_DB
              value: stackjudge
            - name: PGDATA
              value: /data/postgres
---
apiVersion: v1
kind: Service
metadata:
  namespace: stackjudge-master
  name: postgres-service
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: postgres
