############################### Backend App
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stackjudge-master
  name: backend-app
  labels:
    app: backend-app-label
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-app
  template:
    metadata:
      labels:
        app: backend-app-label
        service: backend-app
    spec:
#      restartPolicy: Always
      containers:
        - name: backend-app
          image: kbalazsworks/stackjudge_backend:master
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 400m
              memory: 400Mi
          env:
            - name: SERVER_PORT
              value: "41000"
            - name: SERVER_ENV
              value: "LOCAL_VAGRANT"
            - name: HEALTH_CHECK_ENV_VAR_TEST
              value: "env var test"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://backend-psql-service:41030/stackjudge"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin_pass"
#            - name: IS_SEARCH_BOX_LOG_ENABLED"
#              value: False
            - name: ENV_SEARCHLY_URL
              value: ""
            - name: HTTP_CORS_ORIGINS
              value: "http://localhost:4200"
            - name: SJ_IDS_FULL_HOST
              value: "http://identity-service-app:41050"
#            - name: AWS_S3_CDN_BUCKET
#              value: "stackjudge-cdn-dev-eu-central-1"
#            - name: AWS_ACCESS_KEY
#              value: "AKIA5PU76MZEYED5O2EG"
#            - name: AWS_SECRET_KEY
#              value: "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"
#            - name: FACEBOOK_CLIENT_ID
#              value: "6256044054421319"
#            - name: FACEBOOK_CLIENT_SECRET
#              value: "02d0121396bc2c5f2a3e5713a620a7c2"
#            - name: FACEBOOK_CALLBACK_URL
#              value: "https://192.168.33.10/account/facebook-callbackd"
#            - name: AUTH_JWT_SECRET
#              value: "12345678901234567890123456789012"
#            - name: SITE_DOMAIN
#              value: "https://192.168.33.10"
#            - name: SERVER_SSL_ENABLED
#              value: True
#            - name: SITE_FRONTEND_DOMAIN
#              value: "http://localhost:4200"
            - name: SPRING_REDIS_HOST
              value: "backend-redis-service"
            - name: SPRING_REDIS_PASSWORD
              value: ""
            - name: SPRING_REDIS_PORT
              value: "41060"
#            - name: GOOGLE_MAPS_KEY
#              value: "asd"
#            - name: REDIS_ASPECT_CACHE_ENABLED
#              value: False
#            - name: SERVER_SSL_KEY_STORE
#              value: "classpath:keystore/v2/sjdev.p12"
#            - name: SERVER_SSL_KEY_STORE_PASSWORD
#              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  namespace: stackjudge-master
  name: backend-app
  labels:
    app: backend-app-label
    service: backend-app-service
spec:
  type: LoadBalancer
  selector:
    app: backend-app-label
    service: backend-app
  ports:
    - name: "http"
      protocol: TCP
      port: 41000
      targetPort: 80
---
###
###
### Backend App - PSQL
###
###
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stackjudge-master
  name: backend-psql-deployment
  labels:
    app: backend-psql-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-psql-label
  template:
    metadata:
      labels:
        app: backend-psql-label
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          imagePullPolicy: IfNotPresent
          resources: {}
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin_pass
            - name: POSTGRES_DB
              value: stackjudge
            - name: PGDATA
              value: /data/postgres
---
apiVersion: v1
kind: Service
metadata:
  namespace: stackjudge-master
  name: backend-psql-service
spec:
  type: LoadBalancer
  ports:
    - port: 41030
      targetPort: 5432
  selector:
    app: backend-psql-label
---
###
###
### Backend App - Redis
###
###
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stackjudge-master
  name: backend-redis-deployment
  labels:
    app: backend-redis-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-redis-label
  template:
    metadata:
      labels:
        app: backend-redis-label
    spec:
      containers:
        - name: redis
          image: redis:6.2.6
          ports:
            - containerPort: 6379
          imagePullPolicy: IfNotPresent
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: stackjudge-master
  name: backend-redis-service
spec:
  type: LoadBalancer
  ports:
    - port: 41060
      targetPort: 6379
  selector:
    app: backend-redis-label
---
###############################
###############################
############################### IDS
###############################
###############################
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stackjudge-master
  name: identity-service-app
  labels:
    app: identity-service-app-label
spec:
  replicas: 1
  selector:
    matchLabels:
      service: identity-service-app
  template:
    metadata:
      labels:
        app: identity-service-app-label
        service: identity-service-app
    spec:
      containers:
        - name: identity-service-app
          image: kbalazsworks/stackjudge_identity_service:master
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 400m
              memory: 400Mi
          env:
            - name: env
              value: K8s
---
apiVersion: v1
kind: Service
metadata:
  namespace: stackjudge-master
  name: identity-service-app
  labels:
    app: identity-service-app-label
    service: identity-service-app-service
spec:
  type: LoadBalancer
  selector:
    app: identity-service-app-label
    service: identity-service-app
  ports:
    - name: "http"
      protocol: TCP
      port: 41050
      targetPort: 80
###
###
### IDS - PSQL
###
###
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stackjudge-master
  name: identity-service-postgres-deployment
  labels:
    app: identity-service-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service-postgres
  template:
    metadata:
      labels:
        app: identity-service-postgres
    spec:
      containers:
        - name: identity-service-postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          imagePullPolicy: IfNotPresent
          resources: {}
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin_pass
            - name: POSTGRES_DB
              value: stackjudge
            - name: PGDATA
              value: /data/postgres
---
apiVersion: v1
kind: Service
metadata:
  namespace: stackjudge-master
  name: identity-service-postgres-service
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: identity-service-postgres
