# DEPLOYS

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: kbalazsworks/simple_oidc_ids6_e2e_test:master
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: env
              value: K8s

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          imagePullPolicy: Always
          resources: {}
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin_pass
            - name: POSTGRES_DB
              value: stackjudge
            - name: PGDATA
              value: /data/postgres

---

# SERVICES

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app-service
  ports:
#    - name: "http"
#      protocol: TCP
#      port: 5000
#      targetPort: 5000
#      nodePort: 30000
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
#    - name: "https"
#      protocol: TCP
#      port: 5001
#      targetPort: 5001
#      nodePort: 30001

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: postgres
