apiVersion: v1
kind: ConfigMap
metadata:
  name: insecure-psql-config
  namespace: stackjudge-master
  labels:
    app: backend-psql
    name: insecure-psql-config
data:
  POSTGRES_DB: stackjudge
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin_pass
  postgresql.conf: |
    data_directory = /var/lib/postgresql/data/data-directory
