############################### POSTGRES
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: soidc-test
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          imagePullPolicy: Always
          resources: {}
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin_pass
            - name: POSTGRES_DB
              value: stackjudge
            - name: PGDATA
              value: /data/postgres
---
apiVersion: v1
kind: Service
metadata:
  namespace: soidc-test
  name: postgres-service
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: postgres